version: '3'

services:
    s:
        container_name: leetcode-compete
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "$port:80"

