version: '3'

services:
    s:
        container_name: leetcode-compete
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - MONGODB_USER=$mongodb_user
                - MONGODB_PASSWORD=$mongodb_password
        ports:
            - "$port:80"

